# Generated by Django 3.1.6 on 2021-03-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20210322_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='status',
            field=models.CharField(default='draft', max_length=10),
        ),
    ]
