# Generated by Django 3.1.6 on 2021-03-22 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_activity_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='status',
        ),
    ]
