# Generated by Django 3.1.6 on 2021-03-22 12:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('page', '0004_remove_activity_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='registrations',
            field=models.ManyToManyField(blank=True, default=None, related_name='registration', to=settings.AUTH_USER_MODEL),
        ),
    ]
