# Generated by Django 3.1.6 on 2021-04-05 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_activity_registrations'),
        ('page', '0002_auto_20210322_1050'),
        ('page', '0002_auto_20210322_1045'),
    ]

    operations = [
    ]
