# Generated by Django 3.1.6 on 2021-04-05 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('page', '0006_merge_20210405_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='tidspunkt'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='dato'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='beskrivelse'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='paid',
            field=models.CharField(blank=True, choices=[('B', 'Betalt'), ('G', 'Gratis')], default='G', max_length=1, null=True, verbose_name='betalt'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='place',
            field=models.CharField(choices=[('U', 'Ute'), ('I', 'Inne')], default='U', max_length=1, verbose_name='sted'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(max_length=200, verbose_name='tittel'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
